CREATE DATABASE QuanLyBanHang;
USE QuanLyBanHang;
CREATE TABLE customers(
	cID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    cName VARCHAR(30) NOT NULL,
    cAge INT,
    oID INT,
    FOREIGN KEY (oID) REFERENCES orders(oID)
);
CREATE TABLE orders (
	oID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    oName VARCHAR(30) NOT NULL,
    oDate DATETIME,
    oTotalPrice INT
);
CREATE TABLE products(
	pID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    pName VARCHAR(30) NOT NULL,
    pPrice INT
);
CREATE TABLE orderDetail(
	oID INT AUTO_INCREMENT,
    pID INT AUTO_INCREMENT,
    odQTY INT,
    PRIMARY KEY (oID, pID),
    FOREIGN KEY (oID) REFERENCES orders(oID),
    FOREIGN KEY (pID) REFERENCES products(pID)
);

